/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : MF01.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.061, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-09-09, 14:34, # CodeGen: 47
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : MF01
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**            High Value means ON                          : no
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void MF01_Init(void);
**         Deinit     - void MF01_Deinit(void);
**         On         - void MF01_On(void);
**         Off        - void MF01_Off(void);
**         Neg        - void MF01_Neg(void);
**         Get        - byte MF01_Get(void);
**         Put        - void MF01_Put(byte val);
**         SetRatio16 - void MF01_SetRatio16(word ratio);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/

#ifndef __MF01_H
#define __MF01_H

/* MODULE MF01. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin4.h"

#include "Cpu.h"

#define MF01_ClrVal()    LEDpin4_ClrVal() /* put the pin on low level */
#define MF01_SetVal()    LEDpin4_SetVal() /* put the pin on high level */
#define MF01_SetInput()  LEDpin4_SetInput() /* use the pin as input pin */
#define MF01_SetOutput() LEDpin4_SetOutput() /* use the pin as output pin */

#define MF01_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define MF01_On() LEDpin4_ClrVal()
/*
** ===================================================================
**     Method      :  MF01_On (component LED)
**
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define MF01_Off() LEDpin4_SetVal()
/*
** ===================================================================
**     Method      :  MF01_Off (component LED)
**
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define MF01_Neg() LEDpin4_NegVal()
/*
** ===================================================================
**     Method      :  MF01_Neg (component LED)
**
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define MF01_Get() (!(LEDpin4_GetVal()))
/*
** ===================================================================
**     Method      :  MF01_Get (component LED)
**
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define MF01_Init() MF01_Off()
/*
** ===================================================================
**     Method      :  MF01_Init (component LED)
**
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define MF01_Put(val)  ((val) ? MF01_On() : MF01_Off())
/*
** ===================================================================
**     Method      :  MF01_Put (component LED)
**
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void MF01_Deinit(void);
/*
** ===================================================================
**     Method      :  MF01_Deinit (component LED)
**
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void MF01_SetRatio16(word ratio);
/*
** ===================================================================
**     Method      :  MF01_SetRatio16 (component LED)
**
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END MF01. */

#endif
/* ifndef __MF01_H */
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
