/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : MF02.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.061, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-08-21, 17:47, # CodeGen: 22
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : MF02
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**            High Value means ON                          : no
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void MF02_Init(void);
**         Deinit     - void MF02_Deinit(void);
**         On         - void MF02_On(void);
**         Off        - void MF02_Off(void);
**         Neg        - void MF02_Neg(void);
**         Get        - byte MF02_Get(void);
**         Put        - void MF02_Put(byte val);
**         SetRatio16 - void MF02_SetRatio16(word ratio);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/

#ifndef __MF02_H
#define __MF02_H

/* MODULE MF02. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin5.h"

#include "Cpu.h"

#define MF02_ClrVal()    LEDpin5_ClrVal() /* put the pin on low level */
#define MF02_SetVal()    LEDpin5_SetVal() /* put the pin on high level */
#define MF02_SetInput()  LEDpin5_SetInput() /* use the pin as input pin */
#define MF02_SetOutput() LEDpin5_SetOutput() /* use the pin as output pin */

#define MF02_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define MF02_On() LEDpin5_ClrVal()
/*
** ===================================================================
**     Method      :  MF02_On (component LED)
**
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define MF02_Off() LEDpin5_SetVal()
/*
** ===================================================================
**     Method      :  MF02_Off (component LED)
**
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define MF02_Neg() LEDpin5_NegVal()
/*
** ===================================================================
**     Method      :  MF02_Neg (component LED)
**
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define MF02_Get() (!(LEDpin5_GetVal()))
/*
** ===================================================================
**     Method      :  MF02_Get (component LED)
**
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define MF02_Init() MF02_Off()
/*
** ===================================================================
**     Method      :  MF02_Init (component LED)
**
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define MF02_Put(val)  ((val) ? MF02_On() : MF02_Off())
/*
** ===================================================================
**     Method      :  MF02_Put (component LED)
**
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void MF02_Deinit(void);
/*
** ===================================================================
**     Method      :  MF02_Deinit (component LED)
**
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void MF02_SetRatio16(word ratio);
/*
** ===================================================================
**     Method      :  MF02_SetRatio16 (component LED)
**
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END MF02. */

#endif
/* ifndef __MF02_H */
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
